services:
    - type: web
      name: trello-backend
      runtime: node
      plan: free
      buildCommand: npm install --include=dev && npm run build
      startCommand: npm run start
      autoDeploy: true
