export enum EventType {
    CARD_CREATED = "CARD_CREATED",
    CARD_UPDATED = "CARD_UPDATED",
    CARD_MOVED = "CARD_MOVED",
    CARD_REORDERED = "CARD_REORDERED",
    CARD_ARCHIVED = "CARD_ARCHIVED",
    CARD_RESTORED = "CARD_RESTORED",
    CARD_MEMBER_ASSIGNED = "CARD_MEMBER_ASSIGNED",
    CARD_MEMBER_REMOVED = "CARD_MEMBER_REMOVED",

    BOARD_CREATED = "BOARD_CREATED",
    BOARD_UPDATED = "BOARD_UPDATED",
    BOARD_DELETED = "BOARD_DELETED",

    COMMENT_CREATED = "COMMENT_CREATED",
    COMMENT_UPDATED = "COMMENT_UPDATED",
    COMMENT_DELETED = "COMMENT_DELETED",
}
