export enum AuthErrorCode {
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    VALIDATE_ERROR = 'VALIDATE_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
}
